SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE (A.LENGTH, A.FISH_TYPE) IN (SELECT MAX(C.LENGTH), C.FISH_TYPE
                 FROM FISH_INFO C
                 GROUP BY C.FISH_TYPE)
ORDER BY A.ID;
