SELECT CH.HISTORY_ID, (1 - NVL(P.DISCOUNT_RATE, 0) * 0.01) * CH.DAILY_FEE * CH.PERIOD AS FEE
FROM (SELECT H.HISTORY_ID, H.END_DATE + 1  - H.START_DATE AS PERIOD, C.DAILY_FEE,
      CASE WHEN (H.END_DATE + 1  - H.START_DATE) >= 90 THEN '90일 이상'
      WHEN (H.END_DATE + 1  - H.START_DATE) >= 30 THEN '30일 이상'
      WHEN (H.END_DATE + 1 - H.START_DATE) >= 7 THEN '7일 이상'
      ELSE '할인 없음'
    END AS "TYPE"
     FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
      ON C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭') CH 
      LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
      ON P.DURATION_TYPE = CH.TYPE 
      AND P.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC
